export const prompts = [
	"An abandoned art deco ballroom",
	"A cracked porcelain teacup",
	"A rusted medieval longsword",
	"A bent gold wedding ring",
	"A splintered park bench",
	"A peeling coastal lighthouse",
	"A creased midnight subway ticket",
	"A damaged coronation crown",
	"A smartphone with a shattered screen",
	"A frozen childhood bedroom",
	"A sagging library bookshelf",
	"A scratched astronaut helmet",
	"A traffic light stuck on yellow",
	"A patched wooden canoe",
	"A melting birthday cake",
	"A ruined city snow globe",
	"A flickering vending machine",
	"A dented medieval shield",
	"A roadside motel room",
	"A leaking fountain pen",
	"A broken grand piano",
	"A rain-soaked bus stop",
	"A moldy treasure chest",
	"A torn leather backpack",
	"A dim hospital hallway",
	"A pair of worn running shoes",
	"A deserted gas station",
	"A wooden watchtower",
	"A stalled glass elevator",
	"A dented moving box",
	"A burned movie screen",
	"A warped castle gate",
	"A grocery cart with a bad wheel",
	"A stained lab desk",
	"A child’s crayon drawing",
	"A scratched police badge",
	"A chipped coffee mug",
	"A boarded mountain cabin",
	"A stuck school locker",
	"A tangled fishing net",
	"A broken neon motel sign",
	"A harvested farmer’s field",
	"A cracked train platform",
	"A damaged crystal chandelier",
	"A worn wooden chessboard",
	"A misaligned security camera",
	"A warped playground slide",
	"A cracked museum display case",
	"A pair of broken glasses",
	"A demagnetized hotel keycard",
	"An empty fire extinguisher",
	"A faded roadside billboard",
	"A snow-covered mailbox",
	"A weathered circus tent",
	"A creaking wooden bridge",
	"A water-stained notebook",
	"A dented taxi cab",
	"A scratched courtroom bench",
	"A stack of unopened letters",
	"A rusted riverboat",
	"A flickering streetlamp",
	"A bent satellite dish",
	"A shattered perfume bottle",
	"A narrow prison cell",
	"A chipped skateboard",
	"A cracked carnival mask",
	"A hospital bed with torn sheets",
	"A burned paper map",
	"A gravel-covered city rooftop",
	"A faded vending receipt",
	"A crooked forest treehouse",
	"A dented military helmet",
	"A dusty trophy shelf",
	"A cracked diner booth",
	"A spiral lighthouse staircase",
	"A jammed conveyor belt",
	"A fogged glass terrarium",
	"A wicker picnic basket",
	"A rusted subway turnstile",
	"A cluttered pawn shop display",
	"A splintered wooden gavel",
	"A silent church pew",
	"A dented metal toolbox",
	"A half-empty hotel minibar",
	"A tilted cemetery headstone",
	"A towering floodlight mast",
	"A crushed delivery package",
	"A blinking control panel",
	"A faded roadside motel sign",
	"A cracked museum souvenir",
	"A shattered wall mirror",
	"A sloped parking ramp",
	"A bent library card",
	"A sealed vault door",
	"A dark lighthouse beacon",
	"A tarnished sports trophy",
	"A folded metal chair",
	"A locked leather briefcase",
];
